### ISSUE TITLE
Anyo one has tested this library in Mac OS

### ISSUE THREAD

**Issue by mail2mhossain** [sipsorcery-org/SIPSorceryMedia.FFmpeg#44] opened 2022-09-28 03:44 UTC
Please let me know the ffmpeg version(brew install ffmpeg@4 OR brew install ffmpeg)  and Mac OS version.

**Comment by ChristopheI** [comment] 2022-09-28 06:49
Duplicate of #43 
Please don't intentionally create same tickets

**Closed by ChristopheI** 2022-09-28 06:49 UTC
